"""empty message

Revision ID: 015789d5b515
Revises: 6db149cb393b
Create Date: 2026-09-17 23:56:01.451259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015789d5b515'
down_revision: Union[str, Sequence[str], None] = '6db149cb393b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_secondary', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_phone_secondary'), 'customers', ['phone_secondary'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone_secondary'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.drop_column('customers', 'phone_secondary')
    # ### end Alembic commands ###
