"""empty message

Revision ID: 1aa070f71456
Revises: 4205584e0da2
Create Date: 2026-08-16 21:34:51.289579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aa070f71456'
down_revision: Union[str, Sequence[str], None] = '4205584e0da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_notifications_driver_id'), 'driver_notifications', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_notifications_event_type'), 'driver_notifications', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_notifications_event_type'), table_name='driver_notifications')
    op.drop_index(op.f('ix_driver_notifications_driver_id'), table_name='driver_notifications')
    op.drop_table('driver_notifications')
    # ### end Alembic commands ###
