"""Initial migration

Revision ID: 21a2d1aa2153
Revises: 
Create Date: 2026-09-07 12:00:59.434619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a2d1aa2153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_event_type'), 'admin_notifications', ['event_type'], unique=False)
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('bottle_balance', sa.Integer(), nullable=False),
    sa.Column('prepayment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooler_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('custom_water_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('driver_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_notifications_driver_id'), 'driver_notifications', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_notifications_event_type'), 'driver_notifications', ['event_type'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('price_settings',
    sa.Column('water_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('damaged_bottle_fine', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DRIVER', name='user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('customer_balance_adjustments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('debt_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debt_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prepayment_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prepayment_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_balance_adjustments_customer_id'), 'customer_balance_adjustments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_balance_adjustments_user_id'), 'customer_balance_adjustments', ['user_id'], unique=False)
    op.create_table('drivers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('trip_count', sa.Integer(), nullable=False),
    sa.Column('today_trip_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=True)
    op.create_table('routes',
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='route_status'), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_date'), 'routes', ['date'], unique=False)
    op.create_index(op.f('ix_routes_driver_id'), 'routes', ['driver_id'], unique=False)
    op.create_table('orders',
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ON_WAY', 'DELIVERED', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('delivered_bottles', sa.Integer(), nullable=True),
    sa.Column('returned_bottles', sa.Integer(), server_default='0', nullable=True),
    sa.Column('damaged_bottles', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bottle_balance_after', sa.Integer(), nullable=True),
    sa.Column('bulk_5l_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bulk_5l_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('bulk_10l_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bulk_10l_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('picked_coolers', sa.Integer(), server_default='0', nullable=True),
    sa.Column('picked_bottles', sa.Integer(), server_default='0', nullable=True),
    sa.Column('water_price_applied', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('damaged_fine_applied', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'DEBT', name='payment_method'), nullable=True),
    sa.Column('purpose', sa.Enum('DELIVERY_19L', 'PICKUP', 'BULK_WATER', name='order_purpose'), server_default='DELIVERY_19L', nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('moved_from_route_id', sa.UUID(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['moved_from_route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_moved_from_route_id'), 'orders', ['moved_from_route_id'], unique=False)
    op.create_index(op.f('ix_orders_route_id'), 'orders', ['route_id'], unique=False)
    op.create_table('route_expenses',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FUEL', 'LUNCH', 'REPAIR', 'OTHER', name='expense_category'), server_default='OTHER', nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_expenses_driver_id'), 'route_expenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_route_expenses_route_id'), 'route_expenses', ['route_id'], unique=False)
    op.create_table('payments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'DEBT', name='payment_method'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_recorded_by_user_id'), 'payments', ['recorded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_recorded_by_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_route_expenses_route_id'), table_name='route_expenses')
    op.drop_index(op.f('ix_route_expenses_driver_id'), table_name='route_expenses')
    op.drop_table('route_expenses')
    op.drop_index(op.f('ix_orders_route_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_moved_from_route_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_routes_driver_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_date'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_customer_balance_adjustments_user_id'), table_name='customer_balance_adjustments')
    op.drop_index(op.f('ix_customer_balance_adjustments_customer_id'), table_name='customer_balance_adjustments')
    op.drop_table('customer_balance_adjustments')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('price_settings')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_driver_notifications_event_type'), table_name='driver_notifications')
    op.drop_index(op.f('ix_driver_notifications_driver_id'), table_name='driver_notifications')
    op.drop_table('driver_notifications')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_admin_notifications_event_type'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
