"""empty message

Revision ID: 4205584e0da2
Revises: 00129265b738
Create Date: 2026-08-15 07:19:56.189801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4205584e0da2'
down_revision: Union[str, Sequence[str], None] = '00129265b738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('has_cooler', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('drivers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('customers', 'has_cooler')
    # ### end Alembic commands ###
