"""empty message

Revision ID: 4404eb80508c
Revises: ea535608e061
Create Date: 2026-09-08 22:47:54.568977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4404eb80508c'
down_revision: Union[str, Sequence[str], None] = 'ea535608e061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bottle_sell_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bottle_sell_count')
    # ### end Alembic commands ###
