"""empty message

Revision ID: 6db149cb393b
Revises: 4404eb80508c
Create Date: 2026-09-15 01:39:02.721541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db149cb393b'
down_revision: Union[str, Sequence[str], None] = '4404eb80508c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE delivery_status ADD VALUE IF NOT EXISTS 'CANCELLED'")
    op.add_column('orders', sa.Column('returned_full_bottles', sa.Integer(), server_default='0', nullable=True))
    op.add_column('orders', sa.Column('custom_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('custom_price_set_by_user_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_orders_cancelled_by_user_id'), 'orders', ['cancelled_by_user_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['custom_price_set_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'users', ['cancelled_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('price_settings', 'deposit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_settings', sa.Column('deposit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_cancelled_by_user_id'), table_name='orders')
    op.drop_column('orders', 'cancelled_by_user_id')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'custom_price_set_by_user_id')
    op.drop_column('orders', 'custom_price')
    op.drop_column('orders', 'returned_full_bottles')
    # ### end Alembic commands ###
