"""empty message

Revision ID: b626a67b9740
Revises: 1aa070f71456
Create Date: 2026-08-20 14:59:22.083509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b626a67b9740'
down_revision: Union[str, Sequence[str], None] = '1aa070f71456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_customers', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_customers', 'order')
    # ### end Alembic commands ###
