"""empty message

Revision ID: bd758e814a64
Revises: 015789d5b515
Create Date: 2026-09-19 13:22:38.624872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd758e814a64'
down_revision: Union[str, Sequence[str], None] = '015789d5b515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('completed_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_routes_completed_by_user_id'), 'routes', ['completed_by_user_id'], unique=False)
    op.create_foreign_key(None, 'routes', 'users', ['completed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_index(op.f('ix_routes_completed_by_user_id'), table_name='routes')
    op.drop_column('routes', 'completed_by_user_id')
    # ### end Alembic commands ###
