"""empty message

Revision ID: ea535608e061
Revises: 21a2d1aa2153
Create Date: 2026-09-08 00:47:58.474131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea535608e061'
down_revision: Union[str, Sequence[str], None] = '21a2d1aa2153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bottle_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bottle_balance')
    # ### end Alembic commands ###
